language: java
sudo: false

addons:
  apt:
    packages: &global_deps
      - ksh
      - bison
      - flex
      - gperf
      - libasound2-dev
      - libgl1-mesa-dev
      - libgstreamer0.10-dev
      - libgstreamer-plugins-base0.10-dev
      - libjpeg-dev
      - libpng-dev
      - libx11-dev
      - libxml2-dev
      - libxslt1-dev
      - libxt-dev
      - libxxf86vm-dev
      - pkg-config
      - libavcodec-dev
      - mercurial
      - libgtk2.0-dev
      - libgtk-3-dev
      - libxtst-dev
      - libudev-dev
      - libavformat-dev
      - cmake
      - ruby
      - gdb

# For webkit: t5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev ?
# keep gradle cache.
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer
            - *global_deps
    - os: osx
      osx_image: xcode9
      env:
        - TRAVIS_JAVA_VERSION="9"
        - PRINT_CRASH_LOGS="true"

before_script:
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $GRADLE_OPTS
  # run on xvfb screen (for linux).
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

before_install: .ci/before_install.sh

# skip install stage.
install: true

script: .ci/script.sh

deploy:
  provider: releases
  api_key:
    secure: "XwKiYOfCjaxNGbaCpNVQ067udl4S2/ijCpDhY4WBv6/vDNmAGx40SW8eLuEzm+OH05ch3vvGEp3ajRp1pHEorceXrh4A5aI9FzXI+Zqyg6oRPRSORMPjITyim/66fQFeUKTQPqU2e8u/Tf5HW/n+W/Yv7Q4hoqQtjYF/+d+bq7mp07RdE8s0eP2Flf8G9yRzBC3jCA2p6MpaMaJ7sbZAdtdmIWUoJWOg4qRGKg7NASnc0OOUnGe2V2Cr/Gz4I2tb3m5/OiSqsAmBqgFYxmTeLu1irfrd4jU3m96oBN8ysKqBICwty1HcdGyQvqMLdBolRxNmN0aSnP1eDBH/r9pOR77JlSOaEzltDOtc5iXb4/f6/ufOYA21TAZWuOR3XSoj2iMtuBcq/8yhZB/Ru8rVU+Tml/Wkcj3jthEAjeoXZeHxQs+nV265eEbVsMWgx4jbG0Mwk633yLUm72uMtAaZ3WxWJNJr+up5U586+90v0/8cxATC+uY7NKOEZ423OHSUp4yBQrpFYKlYsshs5uIwarTTC8OQjzRuw+19oBMfRktPUEC6hMBu1acHgLRNuIKrpqSk+KSzwo52YtXA47jrfyIYFJlW65ZjngWb9qKNjEp9CSawvUs+CvHbaCCnYYwadiLD9VxIODPdBxpyP6kxBcWQ9FzO3WnHYyg80tAEbR4="
  skip_cleanup: true
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/images.zip

notifications:
  email: false
