version: "{branch} {build}"

image: Visual Studio 2017

environment:
  matrix:
    - JAVA_VERSION: "8"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

    - JAVA_VERSION: "9"
      JAVA_HOME: C:\jdk9

shallow_clone: true

build:
  verbosity: detailed

build_script:
  - ps: |
      if ($env:JAVA_VERSION -eq "9") {
        choco install jdk9 --version 9.0.1.11 -params 'installdir=C:\\jdk9'
        refreshenv
      }
      choco install pscx
      choco install gradle -version 4.3.1

      # choco install visualstudio2017community --ignorepackagecodes
      # Will need Windows SDK 10.0.26624
      Copy-Item C:\projects\openjfx\.ci\Invoke-Environment.ps1 $PSHome\Modules
      refreshenv

      # Set environment to mimic the Visual Studio command prompt
      Invoke-BatchFile 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat' -Force

      # Install DirectX SDK needed by JavaFX
      $client = new-object net.webclient
      $client.DownloadFile("http://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe", "DXSDK_Jun10.exe")
      Start-Process "DXSDK_Jun10.exe" -ArgumentList "/silent"

      java -version
      .\gradlew --version --no-daemon
      .\gradlew build --no-daemon

      # Try and print crash logs if gradle build returned non-zero exit code
      if ($Result.ExitCode -ne 0) {
        Get-ChildItem -Include hs_err_pid*.log -Recurse | Get-Content
      }

test_script:
  - .\gradlew check --no-daemon

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties
